// src/app/components/Bar/components/MenuProject/components/ButtonSave.vue
<script setup lang="ts">
  import store from '/src/store'
  import { mpvzExporter, downloadFile } from '/src/scripts'

  import IconSave from '~icons/heroicons-solid/save'

  import Button from '/src/components/Button.vue'

  const { t } = useI18n()

  const save = async () =>
    store.projects.selected &&
    downloadFile(await mpvzExporter.export(store.projects.selected))
</script>

<template>
  <Button
    full
    :leftIcon="IconSave"
    :disabled="!store.projects.selected"
    orange
    @click="save"
  >
    {{ t('Save project') }}
  </Button>
</template>

<i18n lang="yaml">
fr:
  'Save project': 'Sauvegarder le projet'
</i18n>

// src/routes/index/components/bar/components/menuProject/components/buttonSave.tsx
import { useI18n } from '@solid-primitives/i18n'

import store from '/src/store'

import { downloadFile, mpvzExporter } from '/src/scripts'

import { Button } from '/src/components'

export default () => {
  const [t] = useI18n()

  const save = async () =>
    store.selectedProject &&
    downloadFile(await mpvzExporter.export(store.selectedProject))

  return (
    <Button
      full
      leftIcon={IconTablerFileDownload}
      disabled={!store.selectedProject}
      onClick={save}
      color="orange"
    >
      {t('Save project')}
    </Button>
  )
}
