// src/app/components/Bar/components/MenuProject/Index.vue
<script setup lang="ts">
  import store from '/src/store'

  import DialogInformations from '/src/components/DialogInformations.vue'

  import ButtonSave from './components/ButtonSave.vue'
  import DialogConfigurations from './components/DialogConfigurations.vue'
  import GroupProjects from './components/GroupProjects.vue'

  const { t } = useI18n()

  const props = defineProps<{
    readonly menu: MenuProps
  }>()
</script>

<template>
  <GroupProjects />
  <DialogInformations
    preID="project-"
    :data="[
      {
        title: t('Informations'),
        fields: store.projects.selected
          ? [
              store.projects.selected.name,
              ...store.projects.selected.information,
            ]
          : [],
      },
      {
        title: t('Hardware'),
        fields: store.projects.selected ? store.projects.selected.hardware : [],
      },
    ]"
  />
  <DialogConfigurations />
  <ButtonSave />
</template>

// src/routes/index/components/bar/components/menuProject/index.tsx
import { useI18n } from '@solid-primitives/i18n'

import store from '/src/store'

// import DialogInformations from '/src/components/dialogInformations'
import ButtonSave from './components/buttonSave'
// import DialogConfigurations from './components/dialogConfigurations'
import GroupProjects from './components/groupProjects'

interface Props {
  readonly menu: MenuProps
}

export default (props: Props) => {
  const [t] = useI18n()

  return (
    <>
      <GroupProjects />
      {/* <DialogInformations
    preID="project-"
    data={[
      {
        title: t('Informations'),
        fields: store.projects.selected
          ? [
              store.projects.selected.name,
              ...store.projects.selected.information,
            ]
          : [],
      },
      {
        title: t('Hardware'),
        fields: store.projects.selected ? store.projects.selected.hardware : [],
      },
    ]}
  />
  <DialogConfigurations /> */}
      <ButtonSave />
    </>
  )
}
