// src/app/components/Bar/components/BarDesktop/components/MenuWrapperDesktop.vue
<script setup lang="ts">
  import { getDisclosureOpenState, setDisclosureOpenState } from '/src/scripts'

  import Disclosure from '/src/components/Disclosure.vue'

  const props = defineProps<{
    readonly icon: any
    readonly name: string
    readonly menuProps: MenuProps
  }>()

  const key = `isDesktopMenu${props.name}Open`
</script>

<template>
  <Disclosure
    :id="props.name"
    :icon="props.icon"
    :text="props.name + props.menuProps.route"
    :defaultOpen="getDisclosureOpenState(key)"
    @click="(open) => setDisclosureOpenState(key, open)"
  >
    <slot></slot>
  </Disclosure>
</template>

// src/routes/index/components/bar/components/barDesktop/components/menuWrapperDesktop.tsx
import { getDisclosureOpenState, setDisclosureOpenState } from '/src/scripts'

import { Details } from '/src/components'

interface Props extends Solid.ParentProps {
  icon: IconProp
  name: string
  menuProps: MenuProps
}

export default (props: Props) => {
  const key = createMemo(() => `isDesktopMenu${props.name}Open`)

  return (
    <Details
      icon={props.icon}
      text={props.name + props.menuProps.route}
      defaultOpen={getDisclosureOpenState(key())}
      onClick={(open) => setDisclosureOpenState(key(), open)}
    >
      {props.children}
    </Details>
  )
}
