// src/app/components/Bar/components/MenuReports/components/DialogExport.vue
<template>
  <Dialog :title="t('Export')" :buttonIcon="CloudDownloadIcon" buttonBlue>
    <template v-slot:button>
      {{ t('Export') }}
    </template>
  </Dialog>
</template>

<script setup lang="ts">
  import { useI18n } from 'vue-i18n'

  import { CloudDownloadIcon } from '@heroicons/vue/solid'

  import { Dialog } from '/src/components'

  const { t } = useI18n()
</script>

<i18n lang="yaml">
en:
  'Export': 'Export'
fr:
  'Export': 'Exporter'
</i18n>

// src/routes/index/components/bar/components/menuReports/components/dialogExport.tsx
import { useI18n } from '@solid-primitives/i18n'

import { Dialog } from '/src/components'

export default () => {
  const [t] = useI18n()

  return (
    <Dialog
      button={{
        leftIcon: IconTablerCloudDownload,
        full: true,
        color: 'orange',
      }}
      title={t('Export report')}
    ></Dialog>
  )
}
